<?php
// index.php - Landing page for DSSM WhatsApp EcoCash Subscription System

echo "<!DOCTYPE html>";
echo "<html lang='en'>";
echo "<head>";
echo "    <meta charset='UTF-8'>";
echo "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
echo "    <title>DSSM WhatsApp EcoCash System</title>";
echo "    <style>";
echo "        body { font-family: Arial, sans-serif; max-width: 800px; margin: 50px auto; padding: 20px; }";
echo "        .status { padding: 10px; margin: 10px 0; border-radius: 5px; }";
echo "        .success { background: #d4edda; color: #155724; border: 1px solid #c3e6cb; }";
echo "        .info { background: #d1ecf1; color: #0c5460; border: 1px solid #bee5eb; }";
echo "        .code { background: #f8f9fa; padding: 10px; border-left: 4px solid #007bff; margin: 10px 0; }";
echo "    </style>";
echo "</head>";
echo "<body>";
echo "    <h1>🎉 DSSM WhatsApp EcoCash Subscription System</h1>";
echo "    <div class='status success'>✅ System Status: ACTIVE</div>";
echo "    <div class='status info'>📱 WhatsApp Webhook: Verified & Running</div>";
echo "";
echo "    <h2>🚀 How It Works</h2>";
echo "    <ol>";
echo "        <li>User sends 'activate' or 'premium' to WhatsApp Business number</li>";
echo "        <li>System generates unique activation code (expires in 5 minutes)</li>";
echo "        <li>User receives code via WhatsApp message</li>";
echo "        <li>User enters code in Flutter app</li>";
echo "        <li>Premium features unlocked for 5 minutes</li>";
echo "    </ol>";
echo "";
echo "    <h2>📊 System Components</h2>";
echo "    <ul>";
echo "        <li><strong>WhatsApp Webhook:</strong> <a href='/src/whatsapp_webhook.php'>/src/whatsapp_webhook.php</a></li>";
echo "        <li><strong>Database:</strong> MySQL on InfinityFree</li>";
echo "        <li><strong>Hosting:</strong> Render.com with Docker</li>";
echo "        <li><strong>Security:</strong> Environment variables & input validation</li>";
echo "    </ul>";
echo "";
echo "    <h2>🔍 Debug & Monitoring</h2>";
echo "    <ul>";
echo "        <li><strong>Incoming Logs:</strong> <a href='/src/logs/whatsapp_incoming.log' target='_blank'>View webhook logs</a></li>";
echo "        <li><strong>Debug Logs:</strong> <a href='/src/logs/debug_get.txt' target='_blank'>View verification logs</a></li>";
echo "    </ul>";
echo "";
echo "    <h2>📱 Test Commands</h2>";
echo "    <div class='code'>";
echo "    # Test webhook verification<br>";
echo "    curl 'https://your-app.onrender.com/src/whatsapp_webhook.php?hub_mode=subscribe&hub_verify_token=dssm_verify_2025&hub_challenge=test123'<br><br>";
echo "";
echo "    # Check system status<br>";
echo "    curl https://your-app.onrender.com/";
echo "    </div>";
echo "";
echo "    <h2>⚙️ Environment Variables</h2>";
echo "    <div class='code'>";
echo "    WHATSAPP_VERIFY_TOKEN=dssm_verify_2025<br>";
echo "    WHATSAPP_ACCESS_TOKEN=[HIDDEN]<br>";
echo "    WHATSAPP_PHONE_NUMBER_ID=879081068623691<br>";
echo "    DB_HOST=sql100.infinityfree.com<br>";
echo "    DB_NAME=if0_40401590_subscriptions_db<br>";
echo "    DB_USER=if0_40401590<br>";
echo "    DB_PASS=[HIDDEN]";
echo "    </div>";
echo "";
echo "    <h2>🗄️ Database Schema</h2>";
echo "    <ul>";
echo "        <li><code>users</code> - User accounts with phone numbers</li>";
echo "        <li><code>payments</code> - EcoCash payment records</li>";
echo "        <li><code>activation_codes</code> - One-time codes with expiry</li>";
echo "        <li><code>unlock_keys</code> - Manual admin-generated unlock keys</li>";
echo "        <li><code>subscriptions</code> - Active subscriptions with dates</li>";
echo "    </ul>";
echo "";
echo "    <h2>🔒 Security Features</h2>";
echo "    <ul>";
echo "        <li>Environment variable configuration</li>";
echo "        <li>Input validation and sanitization</li>";
echo "        <li>Transaction reference uniqueness checks</li>";
echo "        <li>Activation code expiry (5 minutes)</li>";
echo "        <li>Admin dashboard with session authentication</li>";
echo "        <li>One-time unlock keys with time limits</li>";
echo "        <li>Device-specific code validation</li>";
echo "    </ul>";
echo "";
echo "    <h2>🔑 Admin Dashboard</h2>";
echo "    <ul>";
echo "        <li><strong>Admin Access:</strong> <a href='/admin'>/admin</a> (password protected)</li>";
echo "        <li>Generate manual unlock keys for premium features</li>";
echo "        <li>View key usage statistics and history</li>";
echo "        <li>Keys expire in 5 minutes and are one-time use only</li>";
echo "    </ul>";
echo "";
echo "    <footer style='margin-top: 50px; padding-top: 20px; border-top: 1px solid #eee; color: #666;'>";
echo "        <p>🚀 Deployed on Render.com | Built with PHP 8.1 & Docker</p>";
echo "    </footer>";
echo "</body>";
echo "</html>";
?>