<?php
// test_unlock_key.php - Test script for the unlock key system

echo "<h1>🔑 Unlock Key System Test</h1>";

// Test data
$testUserId = "test_user_123";
$testKey = "ABCD-EFGH-IJKL"; // This would be generated by admin

echo "<h2>Test API Call</h2>";
echo "<p>Use this curl command to test the verify_key endpoint:</p>";
echo "<pre>";
echo "curl -X POST https://dssm-webhook.onrender.com/src/verify_key.php \\\n";
echo "  -H 'Content-Type: application/json' \\\n";
echo "  -d '{\"user_id\":\"$testUserId\",\"unlock_key\":\"$testKey\"}'";
echo "</pre>";

echo "<h2>Expected Response (for invalid key)</h2>";
echo "<pre>";
echo "{
  \"success\": false,
  \"error\": \"Invalid or expired unlock key\"
}";
echo "</pre>";

echo "<h2>Expected Response (for valid key)</h2>";
echo "<pre>";
echo "{
  \"success\": true,
  \"message\": \"Premium features unlocked!\",
  \"premium_until\": \"2025-11-29T14:39:52+02:00\",
  \"duration_minutes\": 5
}";
echo "</pre>";

echo "<h2>Admin Dashboard</h2>";
echo "<p>Access the admin dashboard at: <a href='/admin'>/admin</a></p>";
echo "<p>Default password: admin123 (set ADMIN_PASSWORD environment variable)</p>";

echo "<h2>Database Setup</h2>";
echo "<p>Run this SQL to create the unlock_keys table:</p>";
echo "<pre>";
echo file_get_contents('src/schema.sql');
echo "</pre>";
?>